---
- name: Install Filebeat and Metricbeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download filebeat package
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb  
  - name: Install filebeat package
    command: dpkg -i filebeat-7.4.0-amd64.deb
  - name: Copy over filebeat configuration
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml
      mode: '0644'
  - name: Enable and configure system module
    command: filebeat modules enable system
  - name: Setup Filebeat
    command: filebeat setup
  - name: Start Filebeat service
    command: service filebeat start
